[package]
name = "maze_bin"
version = "0.1.0"
authors = ["Richard McCormack <brick@brick.codes>"]
edition = "2018"

[dependencies]
maze_lib = { path = "../maze_lib" }
rand = "0.6"
rand_xorshift = "0.1"
