[package]
name = "maze_lib"
version = "0.1.0"
authors = ["Richard McCormack <brick@brick.codes>"]
edition = "2018"

[dependencies]
rand = "0.6"

[dev-dependencies]
criterion = "0.2"
fxhash = "0.2"
rand_xorshift = "0.1"

[[bench]]
name = "pathfinding"
harness = false
