[package]
name = "maze_lib"
version = "0.1.0"
authors = ["Richard McCormack <brick@brick.codes>"]
edition = "2018"

[dependencies]
rand = "0.7"

[dev-dependencies]
criterion = "0.3"
fxhash = "0.2"
rand_xorshift = "0.2"

[[bench]]
name = "pathfinding"
harness = false
